# Pandas Series
-------------

* * *

What is a Series?
-----------------

A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.

**Example**
```
#Create a simple Pandas Series from a list:

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)
```
* * *

Labels
------

If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

This label can be used to access a specified value.

**Example**
```
#Return the first value of the Series:

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar[0])

```
Create Labels
-------------

With the `index` argument, you can name your own labels.

### Example

Create your own labels:

```
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])  
  
print(myvar)
```
[Try it Yourself »](https://www.w3schools.com/python/pandas/trypython.asp?filename=demo_pandas_series_label)

When you have created labels, you can access an item by referring to the label.

```
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar["y"])
```
* * *

Key/Value Objects as Series
---------------------------

You can also use a key/value object, like a dictionary, when creating a Series.

### Example

Create a simple Pandas Series from a dictionary:
```
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)  
  
print(myvar)
```
[Try it Yourself »](https://www.w3schools.com/python/pandas/trypython.asp?filename=demo_pandas_series_dict)

**Note:** The keys of the dictionary become the labels.

To select only some of the items in the dictionary, use the `index` argument and specify only the items you want to include in the Series.

### Example

Create a Series using only data from "day1" and "day2":

```
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])  
  
print(myvar)
```
[Try it Yourself »](https://www.w3schools.com/python/pandas/trypython.asp?filename=demo_pandas_series_index)

* * *

DataFrames
----------

Data sets in Pandas are usually multi-dimensional tables, called DataFrames.

Series is like a column, a DataFrame is the whole table.

### Example

Create a DataFrame from two Series:
```
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

```
[Try it Yourself »](https://www.w3schools.com/python/pandas/trypython.asp?filename=demo_pandas_series_dataframes)

You will learn about [DataFrames in the next chapter](https://www.w3schools.com/python/pandas/pandas_dataframes.asp).

* * *

Test Yourself With Exercises
----------------------------

[Click to access 3 exercises](https://www.w3schools.com/python/pandas/exercise.asp?filename=exercise_series1)

You can also practice them below in code block

In [6]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2","day3"])

print(myvar)
print(myvar["day2"])

day1    420
day2    380
day3    390
dtype: int64
380

In [2]:
# Create a simple Pandas Series from a list:

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)
print(myvar[2])

0    1
1    7
2    2
dtype: int64
2

In [3]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a,index=["x","y","z"])

print(myvar)
print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7

### Extra: Other ways of Creating Series

There are several ways to create a Pandas series. Here are some of the most common methods:

1. **Creating an empty series**: You can create an empty series using the `pd.Series()` function. For example, `s = pd.Series()` creates an empty series.

2. **Creating a series from a list**: You can create a series from a list using the `pd.Series()` function. For example, `s = pd.Series([1, 2, 3, 4, 5])` creates a series with values `[1, 2, 3, 4, 5]`.

3. **Creating a series from a dictionary**: You can create a series from a dictionary using the `pd.Series()` function. For example, `s = pd.Series({'a': 1, 'b': 2, 'c': 3})` creates a series with values `{'a': 1, 'b': 2, 'c': 3}`.

4. **Creating a series from an array**: You can create a series from an array using the `pd.Series()` function. For example, `s = pd.Series(np.array([1, 2, 3, 4, 5]))` creates a series with values `[1, 2, 3, 4, 5]`.

5. **Creating a series from a scalar value**: You can create a series from a scalar value using the `pd.Series()` function. For example, `s = pd.Series(0, index=[0, 1, 2, 3, 4])` creates a series with values `[0, 0, 0, 0, 0]`.

6. **Creating a series from an existing DataFrame**: You can create a series from an existing DataFrame using the `pd.Series()` function. For example, `s = pd.Series(df['column_name'])` creates a series from the column `column_name` in the DataFrame `df`.



**Sources:**

(1) pandas.Series — pandas 2.2.0 documentation. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html.

(2) Create a Series in python – pandas - DataScience Made Simple. https://www.datasciencemadesimple.com/create-series-in-python-pandas/.

(3) Pandas Series Tutorial with Examples - Spark By {Examples}. https://sparkbyexamples.com/pandas/pandas-series-tutorial-with-examples/.

(4) 2 Easy Ways To Create Pandas Series – The Ultimate Guide. https://data-flair.training/blogs/pandas-series/.

(5) Creating a Pandas Series - GeeksforGeeks. https://www.geeksforgeeks.org/creating-a-pandas-series/.